/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_icmp_ntv_NativeIcmpSocketImpl */

#ifndef _Included_com_icmp_ntv_NativeIcmpSocketImpl
#define _Included_com_icmp_ntv_NativeIcmpSocketImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_icmp_ntv_NativeIcmpSocketImpl
 * Method:    nativeSend
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_icmp_ntv_NativeIcmpSocketImpl_nativeSend
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_icmp_ntv_NativeIcmpSocketImpl
 * Method:    nativeReceive
 * Signature: (Lcom/icmp/IcmpPacket;)V
 */
JNIEXPORT void JNICALL Java_com_icmp_ntv_NativeIcmpSocketImpl_nativeReceive
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_icmp_ntv_NativeIcmpSocketImpl
 * Method:    nativeInit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_icmp_ntv_NativeIcmpSocketImpl_nativeInit
  (JNIEnv *, jobject);

/*
 * Class:     com_icmp_ntv_NativeIcmpSocketImpl
 * Method:    nativeUninit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_icmp_ntv_NativeIcmpSocketImpl_nativeUninit
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
